name: Scala CI

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:

  deploy-snapshot-artifact:

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 11 ]

    runs-on: ubuntu-latest

    env:
      JDK_VERSION: ${{ matrix.jdk }}

    if: ${{ github.event_name == 'push' }}

    steps:
      - id: ks4ayzne88xenjnp
        name: Checkout Code
        uses: actions/checkout@v3
      - id: q4fu92f984mcxgv8
        name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - id: wqktw5whah6d7x86
        name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - id: ryhfp5fnf9zuszg6
        name: Add Sonatype Nexus Credentials
        run: |
          mkdir --parents ${HOME}/.sbt/1.0
          echo 'credentials += Credentials(Path.userHome / ".sbt" / "sonatype_credential")' > ${HOME}/.sbt/1.0/sonatype.sbt
          printf "realm=Sonatype Nexus Repository Manager\nhost=${NEXUS_HOST}\nuser=${NEXUS_USER}\npassword=${NEXUS_PASSWORD}\n" > ${HOME}/.sbt/sonatype_credential
      - id: asdfadsfasdf
        run: ls ${HOME}/.sbt
      - id: asdfadsfasdgadfg
        run: ls ${HOME}/.sbt/1.0
      - id: e96a98y39upwt364
        name: Release Play Silhouette
        run: |
          export SBT_CREDENTIALS=${HOME}/.sbt/sonatype_credential
          sbt +publishSigned
        env:
          NEXUS_HOST: s01.oss.sonatype.org
          NEXUS_PASSWORD:  ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

  deploy-production-artifact:

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 11 ]

    runs-on: ubuntu-latest
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'ref/tags/v') }}

    steps:
      - id: zfkcyysr2ncsk66z
        name: Checkout Code
        uses: actions/checkout@v3
      - id: lrn8hqkvn5e25mzg
        name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - id: qd74w49xtk3uvejh
        name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - id: uptux8s8hua4tryd
        name: Set SBT Credentials Environment Variable
        run: export SBT_CREDENTIALS=${HOME}/.sbt/.sonatype_credentials
      - id: m8mhmxgvzr6w888c
        name: Add Sonatype Nexus Credentials
        run: printf "realm=Sonatype Nexus Repository Manager\nhost=${NEXUS_HOST}\nuser=${NEXUS_USER}\npassword=${NEXUS_PASSWORD}\n" > ${SBT_CREDENTIALS}
      - id: f32bq9vrkfk5earu
        name: Release Play Silhouette
        run: sbt +sonatypeBundleRelease
        env:
          NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
          NEXUS_PASSWORD:  ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
