name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8, 11, 12, 14 ]

    runs-on: ubuntu-latest
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Validating Code Formatting
        run: sbt clean scalariformFormat test:scalariformFormat build:scalariformFormat
      - name: Static Code Check
        run: sbt scapegoat
      - name: Checking Dependencies for Known Vulnerabilities
        run: sbt clean dependencyCheckAggregate
      - name: Checking Dependencies for Updated Versions
        run: sbt clean dependencyUpdates

  test:

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8, 11, 12, 14 ]

    runs-on: ubuntu-latest
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Testing and Generating Documentation
        run: sbt clean coverage +test doc coverageReport
      - name: Aggregate Coverage from Sub-Projects and Upload to Coveralls
        run: sbt +coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
